# Generated by Django 5.1.2 on 2024-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_subscription_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="status",
        ),
    ]
